-- upgrade --
CREATE TABLE IF NOT EXISTS "publishedevent" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(60) NOT NULL,
    "date_created" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "receivedevent" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "message_id" INT NOT NULL,
    "date_received" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "name" VARCHAR(60) NOT NULL,
    "domain" VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
